### ISSUE TITLE
ARM64 Docker image builds

### ISSUE THREAD

**Issue by brianramseyau** [external-secrets/bitwarden-sdk-server#11]
**Is your feature request related to a problem? Please describe.**
Cannot deploy on Raspberry Pi, Apple Silicon, etc.

**Describe the solution you'd like**
Multi-arch builds including ARM

**Describe alternatives you've considered**
N/A

**Additional context**
With ARM clusters and Apple Silicon being more prevalent, it would be nice to have this support sooner rather than later, assuming there are no issues due to upstream.

**Comment by Skarlso** [comment]
The Rust sdk doesn't support arm builds I'm afraid. 😟

**Comment by Skarlso** [comment]
The one this server uses. It's a CGO library where the Rust library creates object files to use here -> https://github.com/bitwarden/sdk-go/tree/main/internal/cinterface/lib

And now that I look at this, it looks like they have arm libs. 😆 😆 

I shall investigate.

**Comment by Skarlso** [comment]
I'll try making some multi-arch docker builds with dockerx.

**Comment by brianramseyau** [comment]
Oh wow, I did not expect such a quick response and action here. Thank you so much 😀

**Comment by Skarlso** [comment]
Ah, don't be so sure about that hahahaha. :D I'll have to figure out how to do it first. :D

**Comment by Skarlso** [comment]
Oh, hopefully it's as easy as adding `platforms: linux/amd64,linux/arm64`. 🤞

**Comment by Skarlso** [comment]
Alright, build is running... let's see. :D

**Comment by Skarlso** [comment]
Well.. that worked. @brianramseyau  can you try please?

**Comment by brianramseyau** [comment]
@Skarlso it's alive! I'm thankful it was a relatively trivial change for this.
Apologies for the long delay in replying.. Life got in the way, hah
I'll continue in the process today where I can to get it all up and running now this bit starts, and ensure its working entirely as expected.

**Comment by brianramseyau** [comment]
@Skarlso I can confirm this is working as expected (was a little rocky with getting the right config, but it ended up being unrelated).
Thanks heaps for such quick enablement on this one, super happy to be up and running.

**Comment by Skarlso** [comment]
No worries! I'm super glad it works indeed. 😁 

I thought I would have to do some fiddling with the libraries but thankfully it all just worked. Heh. 😏
