### ISSUE TITLE
Feature Request: VaultWarden Compatibility

### ISSUE THREAD

**Issue by thefinn93** [external-secrets/bitwarden-sdk-server#18]
**Is your feature request related to a problem? Please describe.**
Reading through [the documentation for how to deploy this](https://external-secrets.io/latest/provider/bitwarden-secrets-manager/), it seems as though it requires a [BitWarden Machine Account](https://bitwarden.com/help/machine-accounts/), which does not seem to be something that VaultWarden supports.

**Describe the solution you'd like**
I'm not sure what the right solution is, but it seems like External Secrets is moving to this server as the official solution for BitWarden access and it would be nice if it supported VaultWarden.

**Describe alternatives you've considered**
I assume I can use the webhook-based bitwarden-cli option that is still documented under [Examples -> BitWarden](https://external-secrets.io/latest/examples/bitwarden/), but that seems to be the older option that will presumably become less supported over time.

It would, of course, be nice if VaultWarden just supported Machine Accounts.

**Comment by Skarlso** [comment]
Yes, VaultWarden has a different thing as is supported by a different thing. :) This server is specifically for Bitwarden Secrets Manager. :) Thanks @volschin for the answer.

**Comment by thefinn93** [comment]
Thanks, I was not at all clear on that. It [seems like](https://github.com/dani-garcia/vaultwarden/discussions/3368) VaultWarden isnt going to add any kind of secrets manager support any time soon, so I'll go ahead and close this.
